---
ID: "6ee8d4da-b699-49d8-970e-73ebf90d20a3"
Parent: "d64c0b98-7f0d-4e22-bfa4-50f813ca45be"
Template: "d64c0b98-7f0d-4e22-bfa4-50f813ca45be"
Path: /sitecore/templates/Project/Learning JSS/MyCP/Form/Folders/States/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{8AC2FB17-F300-4CC3-B753-6BB5C6A8A678}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250220T155840Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
