---
ID: "6c7c6c8f-4f68-4fa5-b74e-03f7e34489eb"
Parent: "5066b657-8c1e-451f-b102-1b43ae2264b7"
Template: "5066b657-8c1e-451f-b102-1b43ae2264b7"
Path: /sitecore/templates/Common/Educity/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240328T150547Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
