---
ID: "41b727ea-46ba-429c-9bef-5ddc62dbbcad"
Parent: "81ca6ca5-a5f3-4471-bfad-4e9f4b1e2c26"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/Learning/Common/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240327T023744Z
