---
ID: "a6baca30-164e-4409-b2b6-221dbfb2faea"
Parent: "8d1d1549-9602-4bfc-aa2a-436790e59f47"
Template: "18d0bd79-7da4-4c2a-a924-b93a2b99d669"
Path: /sitecore/content/Learning/Common/Settings/Shared Sites Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240327T023742Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
