---
ID: "e40cdefd-9879-476b-994a-5c859c7320c7"
Parent: "fe7c2137-ec69-4974-84df-7289ed24f918"
Template: "f1828a2c-7e5d-4bbd-98ca-320474871548"
Path: /sitecore/media library/Project/Learning JSS/MyCP/security
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/E40CDEFD9879476B994A5C859C7320C7.ashx?h=16&thn=1&w=16"
- ID: "22eac599-f13b-4607-a89d-c091763a467d"
  Hint: Width
  Value: 52
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "b464f88f-4a7a-4742-8f04-5baae1fe2801"
  Value: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iNTMiIGhlaWdodD0iNTMiIHZpZXdCb3g9IjAgMCA1MyA1MyI+DQogIDxkZWZzPg0KICAgIDxjbGlwUGF0aCBpZD0iY2xpcC1wYXRoIj4NCiAgICAgIDxyZWN0IGlkPSJSZWN0YW5nbGVfMTQ5NTAwIiBkYXRhLW5hbWU9IlJlY3RhbmdsZSAxNDk1MDAiIHdpZHRoPSIyMiIgaGVpZ2h0PSIyMyIgZmlsbD0iI2ZmZmRlNiIvPg0KICAgIDwvY2xpcFBhdGg+DQogICAgPGNsaXBQYXRoIGlkPSJjbGlwLXBhdGgtMyI+DQogICAgICA8cmVjdCBpZD0iUmVjdGFuZ2xlXzE0OTQ5OCIgZGF0YS1uYW1lPSJSZWN0YW5nbGUgMTQ5NDk4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjUiIGZpbGw9IiMwMzYiLz4NCiAgICA8L2NsaXBQYXRoPg0KICA8L2RlZnM+DQogIDxnIGlkPSJHcm91cF84NTQ3OSIgZGF0YS1uYW1lPSJHcm91cCA4NTQ3OSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE1MC41IC0xNDguNSkiPg0KICAgIDxwYXRoIGlkPSJTaGFwZSIgZD0iTTAsMjZBMjYsMjYsMCwxLDAsMjYsMCwyNi4wMywyNi4wMywwLDAsMCwwLDI2WiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTUxIDE0OSkiIGZpbGw9IiNlYmJmODIiIHN0cm9rZT0iI2ViYmY4MiIgc3Ryb2tlLXdpZHRoPSIxIi8+DQogICAgPGcgaWQ9Ikdyb3VwXzg1NDY1IiBkYXRhLW5hbWU9Ikdyb3VwIDg1NDY1Ij4NCiAgICAgIDxnIGlkPSJHcm91cF84NTQ2NCIgZGF0YS1uYW1lPSJHcm91cCA4NTQ2NCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTY3IDE2NikiPg0KICAgICAgICA8ZyBpZD0iR3JvdXBfODU0NjMiIGRhdGEtbmFtZT0iR3JvdXAgODU0NjMiIGNsaXAtcGF0aD0idXJsKCNjbGlwLXBhdGgpIj4NCiAgICAgICAgICA8ZyBpZD0iR3JvdXBfODU0NjIiIGRhdGEtbmFtZT0iR3JvdXAgODU0NjIiIHN0eWxlPSJpc29sYXRpb246IGlzb2xhdGUiPg0KICAgICAgICAgICAgPGcgaWQ9Ikdyb3VwXzg1NDYxIiBkYXRhLW5hbWU9Ikdyb3VwIDg1NDYxIj4NCiAgICAgICAgICAgICAgPGcgaWQ9Ikdyb3VwXzg1NDYwIiBkYXRhLW5hbWU9Ikdyb3VwIDg1NDYwIiBjbGlwLXBhdGg9InVybCgjY2xpcC1wYXRoKSI+DQogICAgICAgICAgICAgICAgPHBhdGggaWQ9IlBhdGhfODcwMzUiIGRhdGEtbmFtZT0iUGF0aCA4NzAzNSIgZD0iTTIyLDFWOGMwLDEyLTExLDE1LTExLDE1UzAsMjAsMCw4VjFBMSwxLDAsMCwxLDEsMEgyMWExLDEsMCwwLDEsMSwxIiBmaWxsPSIjZmZmZGU2Ii8+DQogICAgICAgICAgICAgIDwvZz4NCiAgICAgICAgICAgIDwvZz4NCiAgICAgICAgICA8L2c+DQogICAgICAgIDwvZz4NCiAgICAgIDwvZz4NCiAgICAgIDxnIGlkPSJHcm91cF84NTQ1OSIgZGF0YS1uYW1lPSJHcm91cCA4NTQ1OSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTY1IDE2NSkiPg0KICAgICAgICA8ZyBpZD0iR3JvdXBfODU0NTgiIGRhdGEtbmFtZT0iR3JvdXAgODU0NTgiIGNsaXAtcGF0aD0idXJsKCNjbGlwLXBhdGgtMykiPg0KICAgICAgICAgIDxwYXRoIGlkPSJQYXRoXzg3MDMyIiBkYXRhLW5hbWU9IlBhdGggODcwMzIiIGQ9Ik0xMywxMnY1YTEsMSwwLDAsMS0yLDBWMTJhMSwxLDAsMCwxLDIsMCIgZmlsbD0iI2VmM2UzMyIvPg0KICAgICAgICAgIDxwYXRoIGlkPSJQYXRoXzg3MDMzIiBkYXRhLW5hbWU9IlBhdGggODcwMzMiIGQ9Ik0xMiw2YTEuNSwxLjUsMCwxLDAsMS41LDEuNUExLjUsMS41LDAsMCwwLDEyLDYiIGZpbGw9IiNlZjNlMzMiLz4NCiAgICAgICAgICA8cGF0aCBpZD0iUGF0aF84NzAzNCIgZGF0YS1uYW1lPSJQYXRoIDg3MDM0IiBkPSJNMjIsMEgyQTIsMiwwLDAsMCwwLDJWOUExNS45MjIsMTUuOTIyLDAsMCwwLDUuODU5LDIxLjc3NGExNy41MTgsMTcuNTE4LDAsMCwwLDUuODc1LDMuMTkxLDEsMSwwLDAsMCwuNTI1LDAsMTcuNDg5LDE3LjQ4OSwwLDAsMCw1Ljg3NS0zLjE5MUExNS45LDE1LjksMCwwLDAsMjQsOVYyYTIsMiwwLDAsMC0yLTJtMCw5YTEzLjgyNiwxMy44MjYsMCwwLDEtNS4wNzQsMTEuMTc3QTE2LjE0LDE2LjE0LDAsMCwxLDEyLDIyLjk1MmExNi4wMTksMTYuMDE5LDAsMCwxLTQuODY2LTIuNzI2QTEzLjgyMSwxMy44MjEsMCwwLDEsMiw5VjJIMjJaIiBmaWxsPSIjMDM2Ii8+DQogICAgICAgIDwvZz4NCiAgICAgIDwvZz4NCiAgICA8L2c+DQogIDwvZz4NCjwvc3ZnPg0K
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 2202
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: image/svg+xml
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: svg
- ID: "de2ca9e4-c117-4c8a-a139-1ff4b199d15a"
  Hint: Height
  Value: 52
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250324T061005Z
    - ID: "65885c44-8fcd-4a7f-94f1-ee63703fe193"
      Hint: Alt
      Value: Banner
