---
ID: "5a4ac5a2-2352-4aae-bae8-16a9d4f9e194"
Parent: "00dc8565-5e31-4ccc-974d-5eafcdc6a791"
Template: "00dc8565-5e31-4ccc-974d-5eafcdc6a791"
Path: /sitecore/templates/Project/Learning JSS/MyCP/FAQ/Question/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {507EBF15-9232-4A4C-8F5F-836730B8BAD2}
    {00DC8565-5E31-4CCC-974D-5EAFCDC6A791}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250220T155840Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
