---
ID: "7499ea96-44c7-41f7-9509-45ff67f62a4d"
Parent: "eb3d8ddb-32d3-4ec4-bb20-32aae2173feb"
Template: "eb3d8ddb-32d3-4ec4-bb20-32aae2173feb"
Path: /sitecore/templates/Project/Learning JSS/MyCP/Form/Folders/Get a Form List/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{50329028-6C3D-4189-A210-26F67CBE242F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250220T155840Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
